### ISSUE TITLE
How to prepare wiggle file for Artemis

### ISSUE THREAD

**Issue by lufuhao** [sanger-pathogens/Artemis#216]
Hi, 
I wonder how to prepare the wiggle file for Artemis v16.0.0?

I used bam2wig in Augustus to convert bam to wig, as follows:

track name=paragon.vs.Bac3DLv2.NnoN.f.bam type=wiggle_0
variableStep chrom=ctg00006_001_A08.flt500_scaffold_1
585 1
586 1
587 1
588 1
589 2
590 2
591 2
592 2
593 2
594 2

but when I add user plot..., it showed some error: error while reading user data: uk.ac.sanger.artemis.io.ReadFormatException: the base position (7840) is greater than the sequence length:
7840 6

when I change to another scaffolds, it would show the similar error but different base num. I guess Artemis try to add all the wiggle to current chr/scaffold. 

Or did I use a wrong way to add wiggle plot? What the right way.

The IGV did not report any error to my wiggle file. that's a little strange?

F

**Comment by kpepper** [comment]
Closing this issue as it's old.
