### ISSUE TITLE
.embl file not working in Artemis

### ISSUE THREAD

**Issue by bineetuwa** [sanger-pathogens/Artemis#222]
Hi, 
I used gubbins in my whole genome alignment containing 9 whole genome sequences of _Helicobacter pylori. _ When I tried to view .gff and .embl file onto any sequence from the alignment in Artemis, there is an error message like this: 
**read failed: one of the features in the entry has out of range location: 1623848..1624333**
Can you please help me fix this ?

**Comment by pjanek** [comment]
Hi,
I'm not an official Artemis developer, but I'm using it from time to time and IMO it's not a bug. Your input file contains a feature with inappropriate location (sequence is shorter than 1624333bp), so there is no meaningful way to display it. Bug is due to Gubbins (or other previously used software if any).

**Comment by andrewjpage** [comment]
Response was sent privately offline, so adding this for the record.  The error isnt in Gubbins or Artemis. 

Expanded query:
>   I am not being able to open .recombination_predictions.embl and .branch_base_reconstruction.embl files on any sequencs from the alignment in Artemis. Following message pops up: read failed: one of the features in the entry has out of range location: 1623848..1624333. That looks quite obvious as the genome size is only 1507542. But because of gaps in the alignment the position of the bases goes up to 1874743 and Gubbins would have analysed based on that. I would be grateful if you could help me by showing any way to fix this.

Why Artemis fails

> A reference of 1507542 is provided to artemis, but the Gubbins recombinations are overlayed on to the alignment which is 1874743 bases in length.

Solution
>  The easiest way to fix this is to extract a sequence from the
> alignment, and use that as a reference onto which the output of Gubbins
> can be read. Artemis can read sequences with gaps, they just show up as
> blank sections in the sequence.
