### ISSUE TITLE
Artemis not opening files with brackets/space/altered name

### ISSUE THREAD

**Issue by AnnaSyme** [sanger-pathogens/Artemis#229]
Hi, 

In Artemis, Graph: Add User Plot will not open a file with brackets in the name: filename snps.depth (1).gz

(This file had the (1) appended when it was re-downloaded to mac). 

Edited to add: the file also won't open with just the space in it (without the (1)) and also with a different name, e.g. snps.dept.gz, but will if these are changed to the (correct) name snps.depth.gz

Artemis (release 16.0.0) on Mac (Sierra 10.12.1)

Thanks!

**Comment by andrewjpage** [comment]
Hi Anna, 
The solution is to rename your file to remove the space. Unix/Linux applications generally don't work too easily when there are spaces in filenames.

Regards,
Andrew

**Comment by AnnaSyme** [comment]
thanks Andrew!
