### ISSUE TITLE
Feature Request: recognize and open multi-genbanks in multiple seperate windows

### ISSUE THREAD

**Issue by jvollme** [sanger-pathogens/Artemis#236]
Artemis alredy can handle opening two seperate genbanks in seperate windows.
However if a multi-genbank file (multiple genbanks concatenated into a single file, seperated by file-end symbols "//") is opened, only the first contig is viewed. All other contigs are ignored.

As it is common practice to handle and store fragmented genomes and genomes with multiple replicons as multi-genbanks, it would be highly convenient if Artemis could recognize and handle such files.

**Comment by tseemann** [comment]
The quick solution is to use GFF3 instead. Artemis works with these when they have multiple contigs. I believe the 1-sequence-per-Genbank is very difficult to implement in Artemis (I spoke to long time maintainer Tim Carver).

**Comment by kpepper** [comment]
Thanks for your comment Torsten. I've recently started working in the Sanger Pathogen Informatics team, on Artemis development. We don't have plans for including multi-genbank support currently but will be working to improve GFF3 support. As **@tseemann** has said it would be best to work with indexed GFF3/fasta in this scenario.

**Comment by tseemann** [comment]
@kpepper when you say `indexed GFF` do you mean I should be using `tabix -p gff` on my files?

**Comment by kpepper** [comment]
**@tseemann** it's optional, and dependent on scenario..... from the Artemis manual:

Indexed GFF3 format. This can be read in and overlaid onto an indexed FASTA file. The indexed GFF3 file contains the feature annotations. To index the GFF first sort and bgzip the file and then use tabix with "-p gff" option (see the tabix manual): 

(grep ^"#" in.gff; grep -v ^"#" in.gff | sort -k1,1 -k4,4n) | bgzip > sorted.gff.gz; 
tabix -p gff sorted.gff.gz 

A drop down menu of the sequences in the Entry toolbar (see the section called A breakdown of the main Artemis edit window in Chapter 3 ) at the top can then used to select the sequence to view. Using indexed FASTA and indexed GFF files improves the memory management and enables large genomes to be viewed. Note that as it is indexed the sequence and annotation are read-only and cannot be edited. When there are many contigs to select from it can be easier to display the one of interest by typing the name into the drop down list. 

Obviously, the gff3 should not have embedded fasta for this process to work.

**Comment by tseemann** [comment]
Ok thanks for the info.  All my GFF3 normally contain sequence (output of my `prokka`).
