### ISSUE TITLE
artemis_compiled_v17.0.1.tar.gz has all MacOS resource forks in it

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/Artemis#239]
FYI - it seems all the MacOS files got into the tar file:

```
artemis/
artemis/._act
artemis/act
artemis/._art
artemis/art
artemis/artemis_sqlmap/
artemis/._bamview
artemis/bamview
artemis/._dnaplotter
artemis/dnaplotter
artemis/etc/
artemis/images/
artemis/lib/
artemis/._Makefile
artemis/Makefile
artemis/org/
artemis/._README.md
artemis/README.md
artemis/._setenv
artemis/setenv
artemis/uk/
artemis/uk/ac/
artemis/uk/ac/sanger/
artemis/uk/ac/sanger/artemis/
artemis/uk/ac/sanger/artemis/._.project
artemis/uk/ac/sanger/artemis/.project
artemis/uk/ac/sanger/artemis/Action.class
artemis/uk/ac/sanger/artemis/._Action.java
artemis/uk/ac/sanger/artemis/Action.java
artemis/uk/ac/sanger/artemis/ActionController.class
artemis/uk/ac/sanger/artemis/._ActionController.java
artemis/uk/ac/sanger/artemis/ActionController.java
artemis/uk/ac/sanger/artemis/ActionVector.class
artemis/uk/ac/sanger/artemis/._ActionVector.java
artemis/uk/ac/sanger/artemis/ActionVector.java
artemis/uk/ac/sanger/artemis/AlignMatch.class
artemis/uk/ac/sanger/artemis/._AlignMatch.java
artemis/uk/ac/sanger/artemis/AlignMatch.java
```

**Comment by kpepper** [comment]
Yes, you're right - I've copied a new artemis_compiled_v17.0.1.tar.gz to the ftp site without the mac files in. Thanks for the info.

**Comment by tseemann** [comment]
In future please don't do that as we have packages made already and this will break the sha256

**Comment by satta** [comment]
As a Debian packager, I'd like to suggest a simple bump of the patch level version number (to 17.0.2) im such cases. The "-1", "-2", ... version  suffixes have a special meaning for us in the Debian world, and would need to be mangled explicitly during packaging when used in upstream versions.

**Comment by kpepper** [comment]
Okay. It would also be helpful if you could both outline your current process for installing/setting up Artemis. Thanks.

**Comment by satta** [comment]
Well, I'm not the original Debian packager for Artemis, just someone who used to work at Sanger and made a few commits to the Artemis codebase. I think either @0xaf1f or @kloetzl is the last Debian uploader ;)

As far as I can remember from looking at the Artemis package is that in Debian we build the .jars, add them to `/usr/share/java` and then install the `art`, `act`, etc. wrappers in `/usr/bin`.
See https://packages.debian.org/stretch/all/artemis/filelist.  In general, something to keep in mind regarding Java stuff and Debian is that in Debian we build _everything_ from source -- so any compiled jars that are included/added to the Artemis upstream code must also be available in Debian, we can't just get them via Maven or the like (no network access available during builds).

**Comment by kloetzl** [comment]
> I think either @0xaf1f or @kloetzl is the last Debian uploader ;)

I only ever fixed one bug, never actually used Artemis.

**Comment by kpepper** [comment]
**@satta** I'd like to change Artemis to use Maven, to make the build easier,  but would obviously like to make sure that it remains Debian compatible. What happens when you are presented with a Maven pom that wants to pull jars/plugins from the Maven internet repository - how do you deal with it? What if a dependent jar isn't available or a version isn't available on Debian? I presume you would still need a tar file with source, scripts etc in or can you/do you build from GitHub?

**Comment by satta** [comment]
> **@satta** I'd like to change Artemis to use Maven, to make the build easier,  but would obviously like to make sure that it remains Debian compatible.

Thanks a lot for your consideration :)

> What happens when you are presented with a Maven pom that wants to pull jars/plugins from the Maven internet repository - how do you deal with it? 

There is some mechanism in place to map these requirements to packages already in Debian, which then would install the necessary jars in `/usr/share/java`. If necessary, a packager would patch upstream's build configuration to look for jars there.

> What if a dependent jar isn't available or a version isn't available on Debian? 

Then the dependency would need to be packaged (again built from source) ;) 
Versions are more painful -- try to depend on the latest version in Debian, as older versions are not available in the Debian archive. Again, in the worst case a packager would need to patch the source to work with the version available in Debian, contacting upstream if necessary.

> I presume you would still need a tar file with source, scripts etc in or can you/do you build from GitHub?

GitHub is fine, there is automation to get release tarballs from here as long as the release is tagged properly.

**Comment by kpepper** [comment]
Okay, thanks for the info.
