### ISSUE TITLE
What's the entry point for Bamview in artemis.jar ?

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/Artemis#240]
I note the JAR file for art, act, dnaplotter and bamview seem to be all the same.

I have entry points for the first 3, but can you tell me what it is for bamview?

```
    inreplace bin/"art", '"$@"', 'uk.ac.sanger.artemis.components.ArtemisMain "$@"'
    inreplace bin/"act", '"$@"', 'uk.ac.sanger.artemis.components.ActMain "$@"'
    inreplace bin/"dnaplotter", '"$@"', 'uk.ac.sanger.artemis.circular.DNADraw "$@"'
```

**Comment by kpepper** [comment]
They're very similar, only a couple of minor differences. Entry point is: 

uk.ac.sanger.artemis.components.alignment.BamView

**Comment by tseemann** [comment]
thank you! will add it to brew package.
