### ISSUE TITLE
Run fails: Could not find or load main class uk.ac.sanger.artemis.components.ArtemisMain\nPermissions: all-permissions ```

### ISSUE THREAD

**Issue by yurivict** [sanger-pathogens/Artemis#261]
It appears that ```\n``` is left in the manifest files instead of the newline?

```
$ art
Starting Artemis with arguments: -mx2g -ms100m -noverify -Djdbc.drivers=org.postgresql.Driver -Dartemis.environment=UNIX  
Error: Could not find or load main class uk.ac.sanger.artemis.components.ArtemisMain\nPermissions: all-permissions
```

FreeBSD 11.1
```
$ java -version
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)
```

**Comment by kpepper** [comment]
Yes, looks like a simple change to the makefile is needed to fix it. I'll do it and push it to master, today or tomorrow.
FYI, there's also a prebuilt unix release at http://sanger-pathogens.github.io/Artemis/Artemis/

**Comment by kpepper** [comment]
You can now get the latest Makefile from master - it contains the fix.

**Comment by yurivict** [comment]
Thanks for fixing it!
