### ISSUE TITLE
Can not use Artemis

### ISSUE THREAD

**Issue by Lily-WL** [sanger-pathogens/Artemis#263]
Dear developer,

I can not use Artemis in my red hat linux system. The error is as follows. Can you help to figure out the reason? Thank you very much.

`[root@ts-rd350 Artemis-master]# ./art`
Starting Artemis with arguments: -mx2g -ms100m -noverify -Djdbc.drivers=org.postgresql.Driver -Dartemis.environment=UNIX  
错误: 找不到或无法加载主类 uk.ac.sanger.artemis.components.ArtemisMain

`[root@ts-rd350 Artemis-master]# make`
CLASSPATH=lib/commons-lang-2.6.jar:lib/biojava.jar:lib/jemAlign.jar:lib/j2ssh/j2ssh-core.jar:lib/ibatis/ibatis-2.3.4.726.jar:lib/ibatis/log4j-1.2.14.jar:lib/postgresql-8.4-701.jdbc3.jar:lib/picard/picard.jar:lib/commons-net-3.6.jar:lib/batik/batik-awt-util.jar:lib/batik/batik-dom.jar:lib/batik/batik-ext.jar:lib/batik/batik-svggen.jar:lib/batik/batik-util.jar:lib/batik/batik-xml.jar:. javac -source 1.8 -target 1.8   uk/ac/sanger/artemis/ExternalProgramMonitor.java
/bin/sh: javac: 未找到命令
make: *** [uk/ac/sanger/artemis/ExternalProgramMonitor.class] 错误 127

**Comment by Lily-WL** [comment]
I find it maybe the problem that I did not set the JAVA environment. After the JAVA_HOME etc. were set as follows, the error is fixed. 

#set java environment  
JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64
PATH=$PATH:$JAVA_HOME/bin  
CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar  
export JAVA_HOME  CLASSPATH  PATH

**Comment by kpepper** [comment]
Yes, that looks like the problem.
