### ISSUE TITLE
"This version of Mac OS X does not support the Apple EAWT."

### ISSUE THREAD

**Issue by lianefernandes** [sanger-pathogens/Artemis#267]
Hi, I'm trying Artemis for the first time on Mac OS 10.14 (Mojave). 

It was successfully installed but on running ./art the introductory window appears and then freezes. The following thrown exception is shown in the terminal: "This version of Mac OS X does not support the Apple EAWT. ApplicationEvent handling has been disabled (java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener)" (full stack trace attached)

Does this mean the Artemis GUI can't be used on the latest Mac OS? Or can I install something to bypass this error? Thanks

[Stack_trace.txt](https://github.com/sanger-pathogens/Artemis/files/2515566/Stack_trace.txt)

**Comment by kpepper** [comment]
Hi, access to the Apple EAWT has been removed in Java 9+. The current release of Artemis runs with Java 8. What version of Java do you have installed? Type:

Java -version

in a terminal window.

**Comment by kpepper** [comment]
I'm assuming that this problem has been resolved. Please re-open if this is not the case.
