### ISSUE TITLE
Problem installing via conda

### ISSUE THREAD

**Issue by kelwyres** [sanger-pathogens/Artemis#284]
Hi, 
I'm really pleased to see that artemis is moving into a conda package but there seems to be a problem with the current version. Looks like conda only supports up to Java version 8 (?). I'm seeing the following error when I run 'conda install -c bioconda artemis':

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - artemis -> openjdk[version='>=9']

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

_________

AND for 'conda search openjdk':

Loading channels: done
# Name                       Version           Build  Channel
openjdk                      8.0.121               0  pkgs/free
openjdk                      8.0.121               1  pkgs/free
openjdk                      8.0.152      h393ad39_1  pkgs/main
openjdk                      8.0.152      he2ab291_0  pkgs/main

**Comment by kpepper** [comment]
Hi @kelwyres, try this:

conda config --add channels bioconda
conda config --add channels conda-forge
conda install artemis

**Comment by kelwyres** [comment]
Thanks. That has worked. I was just missing conda-forge.
Fyi, I had been following the instructions here: https://anaconda.org/bioconda/artemis
Might be worth adding the extra channels commands?
Best,
Kelly

**Comment by kpepper** [comment]
Yes indeed, I'll add them into the documentation. Thanks for the feedback.
