### ISSUE TITLE
no .jar files in Artemis download

### ISSUE THREAD

**Issue by jlebov** [sanger-pathogens/Artemis#285]
Hi, I'm sure this is a very naive problem, but once I download Artemis on my Windows 10 machine and then extract the files, I don't see any .jar files for atremis.jar or act.jar. I can't figure out what's going wrong. Downloading Artemis from github doesn't seem to produce a "artemis-windows-release-{version}.zip" folder but rather produces a "Artemis-master" folder which seems to lac the necessary .jar files to effectively use Artemis. Any help resolving this would be greatly appreciated. 

Thanks!

**Comment by kpepper** [comment]
Hi @jlebov, you need to use the "Windows" link under the Software Availability section on this page: http://sanger-pathogens.github.io/Artemis/. As you've surmised, there are no distributable files on the Github master branch (only on releases). You should be able to unzip the artemis-windows-release-{version}.zip file and they will be in there. If you don't see them, do you see any files at all?

**Comment by jlebov** [comment]
Wow, I can't believe I missed that link. Pretty clear. Very sorry for taking up your time with that, but thank you very much for your response and help! The problem I'm having now is that when I click on the artemis.jar file, I get a notification that says: "Error: A JNI error has occurred, please check your installation and try again". I've tried doing some googling but haven found any obvious answers. Any ideas?

**Comment by kpepper** [comment]
No worries. That JNI error may be because you have the wrong Java version. You need at least 9 and preferably Java 11. If you're not sure of the version, just bring up a DOS cmd window and type _java -version_ into it - that will tell you.

**Comment by jlebov** [comment]
Alright, I got it up and working! I tried to re-download Java yesterday, but was still getting the error. Today, I manually uninstalled Java from my computer, and then installed "jdk-11.0.2_windows-x64_bin.exe". Now everything seems to be working fine. Thanks again for all your help! And sorry for being such a novice.

**Comment by kpepper** [comment]
Excellent. Hope you find Artemis useful. Now you're up and running I'll close the issue off.

**Comment by artani01** [comment]
Hi, I have installed 'jdk-11.0.2_windows-x64_bin.exe' for artemis.jar. but still unable to open and use artemis tool. Please help.

**Comment by puethe** [comment]
Hello @artani01, can you please type the following in a terminal, to find out if Java 11 is installed correctly:
`java -version`
The following website might be useful too: https://stackoverflow.com/questions/52511778/how-to-install-openjdk-11-on-windows (first answer)
