### ISSUE TITLE
unrecognized option

### ISSUE THREAD

**Issue by YiweiZhu** [sanger-pathogens/Artemis#287]
I have just installed artemis via bioconda. When I start act, it exits, showing the errors below:

(base) [zyw@localhost pkgs]$ act
Starting ACT with arguments: -mx2g -ms100m -noverify --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-
UNNAMED -Djdbc.drivers=org.postgresql.Driver -Dartemis.environment=UNIX  Unrecognized option: --add-opens=java.base/java.lang=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

How can I fix it?

**Comment by kpepper** [comment]
Hi **@YiweiZhu**, it looks like you're missing Java. Did you follow the steps on 
the Github pages (http://sanger-pathogens.github.io/Artemis/)? i.e.

conda config --add channels bioconda     (to add the bioconda channel)
conda config --add channels conda-forge  (to add the conda-forge channel)
conda install artemis

Make sure you also have the condo-forge channel subscription (the 2nd statement). Then uninstall and reinstall the artemis package.

**Comment by kpepper** [comment]
You need Java 11 - it should be available in conda-forge (openjdk 11.0.1). First check that you're subscribed to the conda-forge channel using:

conda config --get channels

which for me gives the following:

--add channels 'r'   # lowest priority
--add channels 'defaults'
**--add channels 'conda-forge'**
--add channels 'bioconda'   # highest priority

**Comment by YiweiZhu** [comment]
@kpepper , I check that I have installed openjdk 11.0.1, and gotten conda-forge channel.  
Now I run the act command, it shows:
(base) [zyw@localhost miniconda3]$ act
Starting ACT with arguments: -mx4g -ms100m -noverify --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-
UNNAMED -Djdbc.drivers=org.postgresql.Driver -Dartemis.environment=UNIX  /data3/zyw/miniconda3/bin/java: **symbol lookup error: /data3/zyw/miniconda3/bin/java: undefined symbol: JLI_InitArgProcessing**

Could you figure it out?

**Comment by kpepper** [comment]
What do you get if you type: /data3/zyw/miniconda3/bin/java -version
?

**Comment by YiweiZhu** [comment]
I get the same error:

(base) [zyw@localhost miniconda3]$ java -version
java: symbol lookup error: java: undefined symbol: JLI_InitArgProcessing

**Comment by kpepper** [comment]
When I list my conda packages [conda list] it shows this:

openjdk                   11.0.1            h1de35cc_1014    conda-forge
artemis                   18.0.2                        0    bioconda

What do you have? Do you also have another Java version installed?

**Comment by YiweiZhu** [comment]
Yes, I have another Java-jdk-8.0.92 installed. Do you mean I have to remove this package?

**Comment by kpepper** [comment]
Is that one installed for a specific reason? Via conda or standalone? You shouldn't be seeing the "symbol lookup" error just from doing "java -version" (which has nothing to do with Artemis). Also, do you have a JAVA_HOME variable set? 

**IF** you don't need the Java 8 I would remove it.

**Comment by YiweiZhu** [comment]
Hello @kpepper . I have installed openjdk version 11.0.1, but when I run java -verison command, it shows:

(base) [zyw@localhost miniconda3]$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

in conda list, the version of openjdk is 11.0.1.  and the artemis still cannot run.
Could you give me any suggestion?

**Comment by YiweiZhu** [comment]
Hello, @kpepper . I install java11 in my .bash_profile, and now I can run artemis! Thank you  very much!

**Comment by VoronDM** [comment]
> Hello, @kpepper . I install java11 in my .bash_profile, and now I can run artemis! Thank you very much!

Hi. Cant You answer more in detail, how to install java11?
