### ISSUE TITLE
Cannot install Java 9 on MacOSX

### ISSUE THREAD

**Issue by thorellk** [sanger-pathogens/Artemis#288]
Hi!
When I try to install the latest version it tells me I need Java 9+ to use it. However, the highest version I can access for Mac OSX on java.com page is 8. Do you have any suggestion on how to solve this?
Best wishes,
k

**Comment by kpepper** [comment]
Hi **@thorellk**, instructions for downloading/installing Java 11 and Artemis are provided in the Artemis manual (https://sanger-pathogens.github.io/Artemis/Artemis/artemis-manual.html#_Toc532218859).

**Comment by thorellk** [comment]
Sorry, I only looked at the [Artemis GitHub page.](http://sanger-pathogens.github.io/Artemis/) Thank you for your swift reply!

**Comment by kpepper** [comment]
If you have any problems just email artemis-help@sanger.ac.uk to raise a support ticket.

**Comment by jianshu93** [comment]
I have the same issue. requires java 9, which is strange because only java 8 is available on www.java.com but oracle jre version is now v18, which I am quite confused.

Jianshu
