### ISSUE TITLE
Supported JDKs/JREs

### ISSUE THREAD

**Issue by mwaltonen** [sanger-pathogens/Artemis#290]
Does Artemis work correctly under open source JDKs/JREs such as OpenJDK or Corretto?

Oracle now requires organizations/businesses to license their Java JDK.

**Comment by kpepper** [comment]
Yes, it's tested with OpenJDK 11. It hasn't been tested specifically with Corretto but should be okay. If you decide to use Corretto 11 let me know how it goes.
