### ISSUE TITLE
For windows Error: A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by drs357** [sanger-pathogens/Artemis#292]
Hello when I double click on the .jar file I get the error:

Error: A JNI error has occurred, please check your installation and try again

This is on a windows 10 machine, can someone please help me?

Thanks

**Comment by kpepper** [comment]
What version of the Artemis software do you have installed?
If it's the latest (18.0.2) then you will need Java version 9 or above (**ideally** version 11.0.2) installed. Java can be downloaded from here: http://jdk.java.net/archive/

If you bring up a DOS window and type:

java -version

what version does it show?

You could also try right-clicking on the artemis jar and selecting Open with... Java.

**Comment by drs357** [comment]
Thank you, I needed to update the jdk.

Thank you!

**Comment by BMDeepak** [comment]
Same issue I am working with jdk 1.8.0_291

**Comment by mattbird567** [comment]
I too am experiencing the same problem. When i type java -version into cmd it returns:

`java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) Client VM (build 25.301-b09, mixed mode)`

When i try and open the Artemis.jar file howveer i am still getting theses two errors:

`Error: A JNI error has occured, please check your installation and try again` 
`A Java Exception has occurred`

**Comment by kpepper** [comment]
@mattbird567 - Later versions of Artemis do not work with Java 1.8 (your installed version). You will need to upgrade your Java version, e.g. Java 11 - see the download GitHub page for details.

**Comment by shalenyjlemko** [comment]
> @mattbird567 - Later versions of Artemis do not work with Java 1.8 (your installed version). You will need to upgrade your Java version, e.g. Java 11 - see the download GitHub page for details.

I don't understand something. When I download the latest version of Java from their page, in the control meny it says Java runtime version "1.8. some numbers", and with that installed, if you type "java -version" in cmd, it tells you "version 23.0.1". So what am I missing?
To be clear, I experience the same problem. Artemis doesn't run for me (although it does if I run it from something like MaGe page).
