### ISSUE TITLE
Artemis vs. Java

### ISSUE THREAD

**Issue by jtn-uw** [sanger-pathogens/Artemis#293]
In OS X 10.14 (Mojave) we have installed Open JDK 12.0.1 (confirmed with java - version) and Artemis (3692:32994) repeatedly says "This application requires that Java 9 or later be installed on your computer."   Java path is correct.  

Tried on 2 Macs, one of which had never seen Java or Artemis.  Same error. 

Any hints?

**Comment by kpepper** [comment]
Hi **@jtn-uw**. Install Java 11 from this site:

https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot#x64_mac

Make sure OpenJDK 11 (LTS), Hotspot and Mac are selected. Then hit the Install JDK button.
Reboot and then install/run artemis.

If you want to run from the command line then you can:

cd <your install location, e.g. Applications folder>/Artemis.app/Contents

and then run the script, i.e.

 ./art

A script is provided for each application, so for ACT:

cd <your install location, e.g. Applications folder>/ACT.app/Contents

and then run the script, i.e. 

./act

**Comment by jtn-uw** [comment]
Interesting.  I installed as you said (and rebooted) but then tried to run Artemis.app directly (Applications >Artemis icon) - got same Java error.  Then used command line and all was great. 

For fun, I removed the Java 11 and rebooted and tried again with command line - also fine.

So maybe issue is not Java itself but App icon?

**Comment by jtn-uw** [comment]
Well, I tried that exact command (copy paste) and got an error after reboot:
-bash: export: '-v': not a valid identifier
-bash: export: '-12': not a valid identifier 

It still works to go to the app, open contents and double click on the art Unix executable.   Clicking on the App simply does not work at all.

**Comment by kpepper** [comment]
Apologies, lost some backquotes along the way. It should have been this....
export JAVA_HOME=`/usr/libexec/java_home -v 11` && export PATH="$JAVA_HOME/bin:$PATH" && java -version

**Comment by kpepper** [comment]
Hi **@jtn-uw**,  I've done some testing on the latest Mojave version and I get the same behaviour, i.e a Java version error. There'll be a new Artemis release very shortly that should fix this problem - v18.0.3.

**Comment by jtn-uw** [comment]
Ah, thanks!  I knew I was doing everything you asked.

**Comment by kpepper** [comment]
You can get the release from here:

https://github.com/sanger-pathogens/Artemis/releases/download/v18.0.3/artemis-macosx-release-18.0.3.dmg.gz

The GitHub page download links aren't updated yet.

**Comment by jtn-uw** [comment]
Will do, thanks again.  Do I uninstall old one?

**Comment by kpepper** [comment]
Thanks for reporting the issue. You can delete the old apps or if you want, rename them. Let me know how you get on.

**Comment by jtn-uw** [comment]
Worked perfectly.  No more java complaints.  Thanks for fixing it!

**Comment by kpepper** [comment]
Great. Thanks for the info.

**Comment by deprekate** [comment]
Just tried on 10.15.7 with the Java15 and Artemis 18.0.3 and still get the "this application requires 9..."

**Comment by SLAment** [comment]
Hi! I also got the same error with Artemis 18.2.0, even tho I have installed openjdk 17.0.7 :(

**Comment by kat-myers2** [comment]
Hi! i also have this this issue using the version that you linked. I have Java and JDK downloaded
