### ISSUE TITLE
art is not recognized

### ISSUE THREAD

**Issue by sgt657** [sanger-pathogens/Artemis#307]
Hi,

After a first unsuccessful attempt to install Artemis for Windows (I did try to install Java 11 first), I installed Artemis via Bioconda, following the instructions:
http://sanger-pathogens.github.io/Artemis/Artemis/

It seems everything worked, however, I can't run 'art'.

'art' is not recognized as an internal or external command,
operable program or batch file.

How can I solve this?

Thank you

**Comment by kpepper** [comment]
Hi @sgt657 ,

The Bioconda install is for Linux/Mac only, not Windows.
It should be just a matter of installing Java 11 via AdoptOpenJDK as per GitHub pages, download the Artemis installation package (via GitHub pages link) and unzip it using something like WinZip or 7Zip. You should then be able to double-click on the artemis .jar file to start it. 

Sometimes the double-click doesn't work as Windows may been configured to associate a .jar file with something other than Java. There's some help in the manual if that's the case. Alternatively, you can also run from a dos window, by cd'ing into the unzipped install folder and then running: java -jar artemis.jar
You can create a shortcut or script for that as well if necessary.
