### ISSUE TITLE
Artemis does not start

### ISSUE THREAD

**Issue by Azkayamin** [sanger-pathogens/Artemis#311]
I have the appropriate java version and previously used Artemis version 18.0.2. I have now deleted that version and downloaded the new one but Artemis is not starting on my windows. When I open artemis.jar file, it asks me how I want to open this file and shows applications in my laptop to open it, Please guide me on how to solve this issue. Thank you.
![Untitled](https://user-images.githubusercontent.com/67484686/85900038-8ba82580-b818-11ea-9f77-0f2f393f8d51.png)

**Comment by Aritrajoy** [comment]
Exactly the same problem. Is it solved?

**Comment by kpepper** [comment]
The .jar should be automatically open, so it looks like your Windows doesn't know which program to use to run the artemis jar file. Can you select "Java" if you select the "More Apps" option? You could also try the second part of solution 2 in this article: https://windowsreport.com/jar-files-not-opening-windows-10/. Alternatively, as a quick fix you can create an artemis.bat file in the same directory and just add the following line to it, in a text editor:

java -jar artemis.jar

Then double-click on the .bat file to start instead.

**Comment by Aritrajoy** [comment]
I'm selecting Java in the more apps section but it's still not working.

**Comment by kpepper** [comment]
Did you try the other suggestions? Can you check what Java version you are running using the following in a dos window:

java -version

**Comment by Aritrajoy** [comment]
I'm trying to save it as a .bat file and let's see if that works. I'll let
you know.

Thanking you
Aritrajoy

**Comment by Aritrajoy** [comment]
It is working now. I can open Artemis now and work on it.

Thanks a lot.

Regards,
Aritrajoy Das.

**Comment by kpepper** [comment]
Excellent. You can use the same trick for the other jars if required.
