### ISSUE TITLE
Missing dependency on htsjdk in pom.xml

### ISSUE THREAD

**Issue by pgrt** [sanger-pathogens/Artemis#313]
Hi,

pom.xml does not mention htsjdk in the dependencies, although it is called in the code. I suggest adding

<dependency>
    <groupId>com.github.samtools</groupId>
    <artifactId>htsjdk</artifactId>
    <version>"some_version"</version>
</dependency>

in the dependencies part.

Best,
Pierre

**Comment by kpepper** [comment]
Hi Pierre. It's bundled in the picard jar, which is included as a dependency.

**Comment by pgrt** [comment]
Hi,

Sorry, I missed it... Thanks for showing me!
