### ISSUE TITLE
Bam files in DNAplotter

### ISSUE THREAD

**Issue by NicoBaeza-13** [sanger-pathogens/Artemis#317]
I'm trying to open some bam files in the DNA plotter. 
The bam files contain extracellular DNA sequences aligned to the reference genome. the bamview window of the artemis software let me visualize coverage of the genome, but I'd like to depict it in the whole genome representation of the DNAplotter. 
I've tried to convert bamfiles into different formats but no success.
Is there a format that can be read by DNAplotter that also contains the coverage information?

Thank you

**Comment by kpepper** [comment]
Closing this issue, as it was answered via path-help support ticket.
