### ISSUE TITLE
Second definition of surefire argLine erases the first one

### ISSUE THREAD

**Issue by pgrt** [sanger-pathogens/Artemis#332]
Hi,

Starting from version 18.2.0, I see, in pom.xml:

<argLine>@{surefireArgLine}</argLine>
<argLine>-Dlog4j.configurationFile=file:${project.build.testOutputDirectory}/log4j.properties</argLine>

in the definition of the properties of the surefire plugin. Yet, by doing so, the second definition erases the first one, so that the whole @{surefireArgLine} is skipped.

Using
<argLine>@{surefireArgLine} -Dlog4j.configurationFile=file:${project.build.testOutputDirectory}/log4j.properties</argLine>
instead fixes this.

Regards,

Pierre

**Comment by kpepper** [comment]
This is now fixed in master so closing the issue. Thanks for raising.
